In [28]:
# 1)How to create an empty and a full NumPy array?
import numpy as np
empt = np.empty((4, 3), dtype=int)
print("Empty Array")
print(empt)
ful = np.full([3, 3], 11, dtype=int)
print("\n Full Array")
print(ful)

Empty Array
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

 Full Array
[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [30]:
# 2)Create a Numpy array filled with all zeros

import numpy as np
arr = np.zeros([3, 3], dtype = int) 
print("\nMatrix : \n", arr) 



Matrix : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [31]:
# 3)Create a Numpy array filled with all ones

import numpy as np 
arr = np.ones([4, 4], dtype = int)
print("\nMatrix arr : \n", arr)


Matrix arr : 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [2]:
# Check whether a Numpy array contains a specified row

import numpy
  
# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
  
# view array
print(arr)
  
# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [35]:
# 5)Remove rows in Numpy array that contains non-numeric values?
import numpy as np
arr = np.array([[11, 42, 90],
                [12, np.nan, 45],
                  [41, np.nan, np.nan]])
print("Given array:")
print(arr)
print("\nRemove all rows containing non-numeric elements")
print(arr[~np.isnan(arr).any(axis=1)])

Given array:
[[11. 42. 90.]
 [12. nan 45.]
 [41. nan nan]]

Remove all rows containing non-numeric elements
[[11. 42. 90.]]
