# Linear Algebra

In [2]:
# Determinant of a Matrix
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
from scipy import linalg
linalg.det(A)

3.0

In [3]:
from scipy import linalg
P, L, U= linalg.lu(A)
print (P)
print(L)
print(L)
print(np.dot(L,U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7. 8. 8.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# Eigen values and eigen vectors of this matrix
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)
print(eigen_vectors)

[15.55528261+0.j -1.41940876+0.j -0.13587385+0.j]
[[-0.24043423 -0.67468642  0.51853459]
 [-0.54694322 -0.23391616 -0.78895962]
 [-0.80190056  0.70005819  0.32964312]]


In [6]:
# Solving systems of linear equations can also be done
v= np.array([[2],[3],[5]])
print(v)
s = linalg.solve(A,v)
print(s)

[[2]
 [3]
 [5]]
[[-2.33333333]
 [ 3.66666667]
 [-1.        ]]


In [7]:
# Sparse Linear Algebra
# SciPy has some routines for computing with sparse and potentially vers submodule scipy.sparse.
from scipy import sparse
A = sparse.lil_matrix((1000, 1000))
print(A)
A[0,:100] = np.random.rand(100)
A[1,100:200] = A[0,:100]
A.setdiag(np.random.rand(1000))
print(A)


  (0, 0)	0.5336488187292454
  (0, 1)	0.8976114059657572
  (0, 2)	0.8497881827526955
  (0, 3)	0.5315276272837366
  (0, 4)	0.4964770787658893
  (0, 5)	0.6381419586226698
  (0, 6)	0.8760134012224897
  (0, 7)	0.894364012278176
  (0, 8)	0.8835303526219381
  (0, 9)	0.460868520174714
  (0, 10)	0.5375276627033153
  (0, 11)	0.8830614465209109
  (0, 12)	0.054112862020130215
  (0, 13)	0.4737566425513534
  (0, 14)	0.5752439179967702
  (0, 15)	0.8364965077868332
  (0, 16)	0.6214028958425496
  (0, 17)	0.2785073511916396
  (0, 18)	0.039653566282703445
  (0, 19)	0.3182792147513659
  (0, 20)	0.7656579551391668
  (0, 21)	0.8443389959108533
  (0, 22)	0.7071448742466295
  (0, 23)	0.22303549292360858
  (0, 24)	0.9413044106085648
  (0, 25)	0.586325712320121
  (0, 26)	0.5118484867812427
  (0, 27)	0.05031095420404719
  (0, 28)	0.6306666888422681
  (0, 29)	0.7286106860038996
  (0, 30)	0.01097487829969035
  (0, 31)	0.15828539714696443
  (0, 32)	0.747245353939158
  (0, 33)	0.10668390138352213
  (0, 34)	0.702615

In [8]:
# Linear Algebra for Sparse Matrices
from scipy.sparse import linalg
A.tocsr()
A = A.tocsr()
b = np.random.rand(1000)
ans = linalg.spsolve(A, b)
print(ans)

[-2.00110313e+02 -1.56158449e+02  1.77981811e+00  3.03978614e+00
  4.31926123e-01  3.95386263e-01  1.71428018e+00  2.82895272e+00
  3.69117560e-02  2.94912164e+00  7.19963637e-01  1.30871591e+00
  8.43009358e-01  2.13132963e+00  3.04357307e+00  2.12170214e-01
  2.99317474e+00  1.22706075e+00  1.02311248e+00  2.77174447e+01
  5.03149307e+01  6.87999380e-01  3.53405664e-01  5.07787199e-01
  4.98307354e-01  1.27776104e+00  9.69315844e-01  8.88840923e-01
  9.68919615e-01  1.39564954e+00  8.23282960e-01  2.07137837e+01
  7.77795280e-01  2.26344603e+00  4.52226920e+01  2.96559799e-01
  7.70237719e-01  1.71799390e+00  9.04476358e-01  1.15052309e+00
  5.09852214e-01  1.82097160e+00  1.25269659e+00  5.35404473e-01
  2.82152934e-02  2.01279267e+00  1.75829592e+00  9.77784195e+00
  9.25114184e-01  1.12689290e+00  2.04784299e+00  9.91232052e-01
  4.87394807e-01  5.96525677e-01  1.41560783e+00  1.37038585e+00
  1.31015244e-01  1.07041256e+00  7.88935708e-01  5.57253687e-01
  1.63859783e-01  1.10933

In [9]:
# Integration
#  Single Integraal

import scipy.integrate
f = lambda x:np.exp(-x ** 2)
i = scipy.integrate.quad(f, 0, 1)
print(i)

(0.7468241328124271, 8.291413475940725e-15)


In [10]:
# Double Integral

from scipy import integrate
f = lambda y, x: x*y**2
i = integrate.dblquad(f, 0, 2, lambda x: 0, lambda x:1)
print(i)

(0.6666666666666667, 7.401486830834377e-15)
