## Different Choices for Indexing

In [4]:
import pandas as pd
import numpy as np
dates = pd.date_range('1/1/2000', periods = 8)

df = pd.DataFrame(np.random.randn(8,4),
        index = dates, columns = ['A', 'B', 'C', 'D'])
df

A         B         C         D
2000-01-01  0.885842 -0.990184  0.641666  1.624324
2000-01-02  0.064358 -1.445551 -0.376869  0.165259
2000-01-03 -2.114569 -1.101279  1.242518  0.525808
2000-01-04 -0.942555  1.321236  1.869850 -0.820214
2000-01-05 -0.415849  0.534507  0.281293 -0.940219
2000-01-06  0.888184  0.260039  0.949793 -1.323621
2000-01-07  0.991666  0.490283  0.596531  1.718358
2000-01-08 -1.747927 -0.508563 -0.018172  0.008909

In [5]:
s = df['A']
s[dates[5]]

0.8881836245749579

In [6]:
df[['B', 'A']] = df[['A', 'B']]
df

A         B         C         D
2000-01-01 -0.990184  0.885842  0.641666  1.624324
2000-01-02 -1.445551  0.064358 -0.376869  0.165259
2000-01-03 -1.101279 -2.114569  1.242518  0.525808
2000-01-04  1.321236 -0.942555  1.869850 -0.820214
2000-01-05  0.534507 -0.415849  0.281293 -0.940219
2000-01-06  0.260039  0.888184  0.949793 -1.323621
2000-01-07  0.490283  0.991666  0.596531  1.718358
2000-01-08 -0.508563 -1.747927 -0.018172  0.008909

In [7]:
df.loc[:, ['B', 'A']] = df[['A', 'B']]
df[['A', 'B']]

A         B
2000-01-01 -0.990184  0.885842
2000-01-02 -1.445551  0.064358
2000-01-03 -1.101279 -2.114569
2000-01-04  1.321236 -0.942555
2000-01-05  0.534507 -0.415849
2000-01-06  0.260039  0.888184
2000-01-07  0.490283  0.991666
2000-01-08 -0.508563 -1.747927

In [8]:
df.loc[:, ['B', 'A']] = df[['A', 'B']].to_numpy()
df[['A', 'B']]

A         B
2000-01-01  0.885842 -0.990184
2000-01-02  0.064358 -1.445551
2000-01-03 -2.114569 -1.101279
2000-01-04 -0.942555  1.321236
2000-01-05 -0.415849  0.534507
2000-01-06  0.888184  0.260039
2000-01-07  0.991666  0.490283
2000-01-08 -1.747927 -0.508563

## Attribute Access

In [9]:
sa = pd.Series([1,2,3], index = list('abc'))
dfa = df.copy()
sa.b
dfa.A

2000-01-01    0.885842
2000-01-02    0.064358
2000-01-03   -2.114569
2000-01-04   -0.942555
2000-01-05   -0.415849
2000-01-06    0.888184
2000-01-07    0.991666
2000-01-08   -1.747927
Freq: D, Name: A, dtype: float64

In [11]:
sa.a = 5
sa

a    5
b    2
c    3
dtype: int64

In [15]:
dfa.A = list(range(len(dfa.index)))
dfa
print("\n")
dfa['A'] = list(range(len(dfa.index)))
dfa

A         B         C         D
2000-01-01  0 -0.990184  0.641666  1.624324
2000-01-02  1 -1.445551 -0.376869  0.165259
2000-01-03  2 -1.101279  1.242518  0.525808
2000-01-04  3  1.321236  1.869850 -0.820214
2000-01-05  4  0.534507  0.281293 -0.940219
2000-01-06  5  0.260039  0.949793 -1.323621
2000-01-07  6  0.490283  0.596531  1.718358
2000-01-08  7 -0.508563 -0.018172  0.008909

In [16]:
x = pd.DataFrame({'x':[1,2,3], 'y':[3,4,5]})
x.iloc[1] = {'x':9, 'y':99}
x

x   y
0  1   3
1  9  99
2  3   5

In [17]:
df = pd.DataFrame({'one':[1,2,3]})
df.two = [4,5,6]
df

C:\Users\iasms\AppData\Local\Temp/ipykernel_9716/1662120914.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.two = [4,5,6]


one
0    1
1    2
2    3

## slicing ranges

In [18]:
s[:5]

2000-01-01    0.885842
2000-01-02    0.064358
2000-01-03   -2.114569
2000-01-04   -0.942555
2000-01-05   -0.415849
Freq: D, Name: A, dtype: float64

In [19]:
s[::2]

2000-01-01    0.885842
2000-01-03   -2.114569
2000-01-05   -0.415849
2000-01-07    0.991666
Freq: 2D, Name: A, dtype: float64

In [20]:
s[::-1]

2000-01-08   -1.747927
2000-01-07    0.991666
2000-01-06    0.888184
2000-01-05   -0.415849
2000-01-04   -0.942555
2000-01-03   -2.114569
2000-01-02    0.064358
2000-01-01    0.885842
Freq: -1D, Name: A, dtype: float64

In [21]:
s2 = s.copy()
s2[:5] = 0
s2

2000-01-01    0.000000
2000-01-02    0.000000
2000-01-03    0.000000
2000-01-04    0.000000
2000-01-05    0.000000
2000-01-06    0.888184
2000-01-07    0.991666
2000-01-08   -1.747927
Freq: D, Name: A, dtype: float64

## Selection by Labels

In [3]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame(np.random.randn(5,4),
                  columns = list('ABCD'),
                  index = pd.date_range('20130101', periods = 5))
df1

A         B         C         D
2013-01-01  0.802512 -1.377943 -1.695772 -0.423109
2013-01-02 -0.832959  0.681069 -1.890558 -0.516817
2013-01-03  1.155526 -2.384199  0.924032  2.071721
2013-01-04 -0.043358  1.415471 -0.225071 -0.878842
2013-01-05 -0.021364  0.471428 -0.183545 -0.636069

In [5]:
# df1.loc[2:3]
df1.loc['20130102':'20130104']

A         B         C         D
2013-01-02 -0.832959  0.681069 -1.890558 -0.516817
2013-01-03  1.155526 -2.384199  0.924032  2.071721
2013-01-04 -0.043358  1.415471 -0.225071 -0.878842

In [25]:
s1 = pd.Series(np.random.randn(6), index = list('abcdef'))
s1

a   -1.042089
b    1.050456
c   -0.132692
d   -0.205094
e   -0.148566
f   -0.710314
dtype: float64

In [26]:
s1.loc['c'] = 0
s1

a   -1.042089
b    1.050456
c    0.000000
d   -0.205094
e   -0.148566
f   -0.710314
dtype: float64

In [27]:
df1 = pd.DataFrame(np.random.randn(6,4),
                  index = list('abcdef'),
                  columns = list('ABCD'))
df1
df1.loc[['a','b', 'c', 'd'],:]

A         B         C         D
a -1.145554  1.606129  0.017194 -1.916876
b  1.947238 -0.478085  0.320546  0.209831
c -1.195255  0.691276  1.846929  0.597357
d  0.153189  0.350222 -0.692985  0.098178

In [28]:
# Acessing via label slices
df1.loc['d':, 'A':'C']

A         B         C
d  0.153189  0.350222 -0.692985
e  0.728556  0.378682  0.407361
f  0.320515  0.968619  0.025340

In [29]:
# for getting a cross section using a label(equivalent to df.xs('a')):
df1.loc['a']

A   -1.145554
B    1.606129
C    0.017194
D   -1.916876
Name: a, dtype: float64

In [30]:
# Slicing with labels
s = pd.Series(list('abcde'), index = [0,3,2,5,4])
s.loc[3:5]

3    b
2    c
5    d
dtype: object

## Sort

In [31]:
s.sort_index()

0    a
2    c
3    b
4    e
5    d
dtype: object

In [32]:
s.sort_index().loc[1:6]

2    c
3    b
4    e
5    d
dtype: object

## Selection by callable 

In [33]:
df1 = pd.DataFrame(np.random.randn(6,4),
                  index = list('abcdef'),
                  columns = list('ABCD'))
df1

A         B         C         D
a -0.752531  2.256892 -0.384629  1.359326
b  0.960020  1.770041 -0.576560 -0.197762
c  0.853654  0.302991 -0.074204 -1.936726
d  0.268849  0.506558 -0.212952 -1.242984
e  0.143126  0.641952  0.246004 -1.048178
f  0.156267 -0.320817 -0.979060 -0.216965

In [34]:
df1.loc[lambda df: df['A'] > 0,:]

A         B         C         D
b  0.960020  1.770041 -0.576560 -0.197762
c  0.853654  0.302991 -0.074204 -1.936726
d  0.268849  0.506558 -0.212952 -1.242984
e  0.143126  0.641952  0.246004 -1.048178
f  0.156267 -0.320817 -0.979060 -0.216965

In [35]:
df1.loc[:, lambda df:['A', 'B']]

A         B
a -0.752531  2.256892
b  0.960020  1.770041
c  0.853654  0.302991
d  0.268849  0.506558
e  0.143126  0.641952
f  0.156267 -0.320817

In [36]:
df1.iloc[:, lambda df:[0,1]] 

A         B
a -0.752531  2.256892
b  0.960020  1.770041
c  0.853654  0.302991
d  0.268849  0.506558
e  0.143126  0.641952
f  0.156267 -0.320817

In [37]:
df1[lambda df: df.columns[0]]

a   -0.752531
b    0.960020
c    0.853654
d    0.268849
e    0.143126
f    0.156267
Name: A, dtype: float64

In [39]:
import pandas as pd
bb = pd.read_csv("C:\\Users\\iasms\\Desktop\\Python Prograamms\\Niyati\\Data Files\\word-prevalence.csv")
(bb.groupby(['Count', 'Prevalence']).sum()
    .loc[lambda df: df['FreqZipfUS']>8])


FreqZipfUS
Count Prevalence            
1     -0.574           9.590
3      0.495           8.314
       0.697          11.584
       1.258           8.219
       2.104           8.110
...                      ...
14     2.240           8.730
       2.335           8.118
       2.576          29.960
15     2.431           8.414
       2.576          13.742

[3187 rows x 1 columns]

## Indexing With List with  missing Labels is Depreceated

In [11]:
s = pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
s.loc[[1,2]]

1    2
2    3
dtype: int64

In [13]:
s.loc[[1,2,3]]

1    2
2    3
3    4
dtype: int64

In [16]:
s.loc[[3,4,4]]

3    4
4    5
4    5
dtype: int64

### reindexing

In [14]:
s.reindex([1,2,3])

1    2
2    3
3    4
dtype: int64

## selecting random samples

In [44]:
s = pd.Series([0, 1, 2, 3, 4, 5])
s.sample()

1    1
dtype: int64

In [45]:
s.sample(n=3)

4    4
0    0
1    1
dtype: int64

In [46]:
s.sample(frac = 0.5)

1    1
3    3
2    2
dtype: int64

In [17]:
s = pd.Series([0, 1, 3, 4, 5, 6, 9, 7, 6])
s.sample(n=6, replace=False)

6    9
3    4
7    7
1    1
4    5
0    0
dtype: int64

In [18]:
s.sample(n=6, replace=True)

5    6
0    0
6    9
4    5
2    3
4    5
dtype: int64

## indexing with isin

In [53]:
s = pd.Series(np.arange(5), index = np.arange(5)[::-1], dtype = 'int64')
s

4    0
3    1
2    2
1    3
0    4
dtype: int64

In [54]:
s.isin([2,4,6])

4    False
3    False
2     True
1    False
0     True
dtype: bool

In [55]:
s[s.isin([2,4,6])]

2    2
0    4
dtype: int64

In [56]:
s[s.index.isin([2,4,6])]

4    0
2    2
dtype: int64

In [57]:
s.reindex([2,4,6])

2    2.0
4    0.0
6    NaN
dtype: float64

## The WHERE() Method

In [58]:
# to return only selected rows
s[s > 0]

3    1
2    2
1    3
0    4
dtype: int64

In [59]:
# to return a Series of the same shape as the original
s.where(s > 0)

4    NaN
3    1.0
2    2.0
1    3.0
0    4.0
dtype: float64

# PANDAS.INDEX.ISIN

In [20]:
idx = pd.Index([1,2,3])
idx

Int64Index([1, 2, 3], dtype='int64')

In [22]:
# check whether each index value in a list of values
idx.isin([1,4])

array([ True, False, False])

In [23]:
midx = pd.MultiIndex.from_arrays([[1,2,3],
                                 ['red', 'blue', 'green']],
                                  names = ('number', 'color'))
midx

MultiIndex([(1,   'red'),
            (2,  'blue'),
            (3, 'green')],
           names=['number', 'color'])

In [24]:
# check whether the strings in the 'color' level of the Multiindex are in a list of colors 
midx.isin(['red', 'orange', 'yellow'], level = 'color')

array([ True, False, False])

In [26]:
# check across the levels of Multiindex, pass a list of tuples
midx.isin([(1, 'red'), (3, 'red')])

array([ True, False, False])

In [73]:
df = pd.DataFrame({'vals': [1,2,3,4], 'ids': ['a', 'b', 'f', 'n'],
                  'ids2': ['a', 'c','n', 'n']})
values = ['a', 'b', 1, 3]
df.isin(values)

vals    ids   ids2
0   True   True   True
1  False   True  False
2   True  False  False
3  False  False  False

In [76]:
df3 = pd.DataFrame({'A': [1,2,3],
                   'B': [4,5,6],
                   'C': [7,8,9]})
df3.where(lambda x:x>4,lambda x:x+10)

A   B  C
0  11  14  7
1  12   5  8
2  13   6  9

# Setting with Enlargement Conditionality using NUMPY()

In [77]:
df = pd.DataFrame({'col1':list('ABBC'), 'col2':list('ZZXY')})
df['color'] = np.where(df['col2'] == 'Z', 'green', 'red')
df

col1 col2  color
0    A    Z  green
1    B    Z  green
2    B    X    red
3    C    Y    red

In [78]:
conditions = [(df['col2'] == 'Z') & (df['col1'] == 'A'),
             (df['col2'] == 'Z') & (df['col1'] == 'B'),
             (df['col1'] == 'B')]
choices = ['yellow', 'blue', 'purple']
df['color'] = np.select(conditions, choices, default = 'black')
df

col1 col2   color
0    A    Z  yellow
1    B    Z    blue
2    B    X  purple
3    C    Y   black

# The Query Method

In [79]:
n = 10
df = pd.DataFrame(np.random.rand(n,3), columns = list('abc'))
df

a         b         c
0  0.072080  0.536170  0.169728
1  0.714308  0.539805  0.027517
2  0.285209  0.770271  0.725182
3  0.510820  0.127465  0.981893
4  0.041139  0.544194  0.788539
5  0.735149  0.220532  0.284879
6  0.764546  0.758817  0.689554
7  0.669085  0.750704  0.364303
8  0.464035  0.732898  0.183105
9  0.275715  0.163372  0.942687

In [80]:
# pure python
df[(df['a'] < df['b']) & (df['b'] < df['c'])]

a         b         c
4  0.041139  0.544194  0.788539

In [81]:
# query
df.query('(a<b) & (b<c)')

a         b         c
4  0.041139  0.544194  0.788539

In [82]:
f = pd.DataFrame(np.random.randint(n/2, size=(n,2)), columns = list('bc'))
df.index.name = 'a'
df
df.query('a<b and b<c')

a         b         c
a                              
4  0.041139  0.544194  0.788539

In [84]:
df = pd.DataFrame(np.random.randint(n, size=(n,2)), columns = list('bc'))
df
df.query('index < b < c')

b  c
0  6  9
3  4  8

# Multiindex Query() Syntax

In [91]:
n = 10
colors = np.random.choice(['red', 'green'], size = n)
foods = np.random.choice(['eggs', 'ham'], size = n)
index = pd.MultiIndex.from_arrays([colors, foods], names = ['color', 'food'])
df = pd.DataFrame(np.random.randn(n,2), index=index)
df
df.query('color == "red"')

0         1
color food                    
red   eggs  0.076212  0.442133
      eggs  0.499043  0.675987
      eggs  0.872918 -0.532156
      eggs -0.145900  1.008780
      ham   0.838075 -1.707307

### the in and not in operators

In [93]:
df = pd.DataFrame({'a': list('aabbccddeeff'), 'b': list('aaaabbbbcccc'),
                          'c': np.random.randint(5, size=12),
                            'd': np.random.randint(9, size=12)})
df
df.query('a in b')

a  b  c  d
0  a  a  4  6
1  a  a  0  3
2  b  a  3  8
3  b  a  2  1
4  c  b  2  8
5  c  b  0  7

In [94]:
df[df['a'].isin(df['b'])]

a  b  c  d
0  a  a  4  6
1  a  a  0  3
2  b  a  3  8
3  b  a  2  1
4  c  b  2  8
5  c  b  0  7

In [95]:
df.query('a not in b')

a  b  c  d
6   d  b  3  8
7   d  b  1  1
8   e  c  0  3
9   e  c  2  3
10  f  c  4  4
11  f  c  4  0

In [96]:
# pure python
df[~df['a'].isin(df['b'])]

a  b  c  d
6   d  b  3  8
7   d  b  1  1
8   e  c  0  3
9   e  c  2  3
10  f  c  4  4
11  f  c  4  0

In [97]:
# rows where cols a and b have overlapping values
# and col c's values are less than col d's
df.query('a in b and c<d')

a  b  c  d
0  a  a  4  6
1  a  a  0  3
2  b  a  3  8
4  c  b  2  8
5  c  b  0  7

In [98]:
# pure python
df[df['b'].isin(df['a']) & (df['c'] < df['d'])]

a  b  c  d
0  a  a  4  6
1  a  a  0  3
2  b  a  3  8
4  c  b  2  8
5  c  b  0  7
6  d  b  3  8
8  e  c  0  3
9  e  c  2  3

## Special use of the == operator with list Objects

In [99]:
df.query('b == ["a","b","c"]')

a  b  c  d
0   a  a  4  6
1   a  a  0  3
2   b  a  3  8
3   b  a  2  1
4   c  b  2  8
5   c  b  0  7
6   d  b  3  8
7   d  b  1  1
8   e  c  0  3
9   e  c  2  3
10  f  c  4  4
11  f  c  4  0

In [104]:
# pure python
df[df['b'].isin(["a","b","c"])]
df.query('c == [1,2]')

a  b  c  d
3  b  a  2  1
4  c  b  2  8
7  d  b  1  1
9  e  c  2  3

In [107]:
df.query('c != [1,2]')

a  b  c  d
0   a  a  4  6
1   a  a  0  3
2   b  a  3  8
5   c  b  0  7
6   d  b  3  8
8   e  c  0  3
10  f  c  4  4
11  f  c  4  0

In [106]:
df[df['b'].isin(["a","b","c"])]
df.query('c == [1,2]')
df.query('c != [1,2]')

a  b  c  d
0   a  a  4  6
1   a  a  0  3
2   b  a  3  8
5   c  b  0  7
6   d  b  3  8
8   e  c  0  3
10  f  c  4  4
11  f  c  4  0

In [108]:
# using in/ not in
df.query('[1,2] in c')

a  b  c  d
3  b  a  2  1
4  c  b  2  8
7  d  b  1  1
9  e  c  2  3

In [109]:
df.query('[1,2] not in c')

a  b  c  d
0   a  a  4  6
1   a  a  0  3
2   b  a  3  8
5   c  b  0  7
6   d  b  3  8
8   e  c  0  3
10  f  c  4  4
11  f  c  4  0

In [110]:
df.query('[1,2] in c')
df.query('[1,2] not in c')

a  b  c  d
0   a  a  4  6
1   a  a  0  3
2   b  a  3  8
5   c  b  0  7
6   d  b  3  8
8   e  c  0  3
10  f  c  4  4
11  f  c  4  0

In [111]:
# pure python
df[df['c'].isin([1,2])]

a  b  c  d
3  b  a  2  1
4  c  b  2  8
7  d  b  1  1
9  e  c  2  3

## DUPLICATE DATA

In [112]:
df1 = pd.DataFrame({'a': ['one', 'one', 'two', 'two', 'two', 'three', 'four'],
                   'b': ['x', 'y', 'x', 'y', 'x', 'x', 'x'],
                   'c': np.random.randn(7)}) 
df1
df1.duplicated('a')
df1.duplicated('a', keep = 'last')
df1.duplicated('a', keep = False)

0     True
1     True
2     True
3     True
4     True
5    False
6    False
dtype: bool

In [114]:
df1.duplicated(['a', 'b'])

0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [115]:
df1.drop_duplicates(['a', 'b'])

a  b         c
0    one  x  0.494032
1    one  y -0.004511
2    two  x  0.334214
3    two  y -3.586337
5  three  x  0.295702
6   four  x  0.946016

In [116]:
df2 = pd.DataFrame({'a': np.arange(6),
                   'b': np.random.randn(6)},
                  index = ['a', 'a', 'b', 'c', 'b', 'a'])
df2

a         b
a  0  1.572142
a  1  0.870764
b  2  0.179087
c  3 -0.359470
b  4  0.356694
a  5 -0.638741

In [117]:
df2.index.duplicated()

array([False,  True, False, False,  True,  True])

In [118]:
df2[~df2.index.duplicated()]

a         b
a  0  1.572142
b  2  0.179087
c  3 -0.359470

In [120]:
df2[~df2.index.duplicated(keep='last')]

a         b
c  3 -0.359470
b  4  0.356694
a  5 -0.638741

In [121]:
df2[~df2.index.duplicated(keep=False)]

a        b
c  3 -0.35947

### Setting Metadata

In [122]:
ind = pd.Index([1,2,3])
ind.rename("apple")

Int64Index([1, 2, 3], dtype='int64', name='apple')

In [125]:
ind

Int64Index([1, 2, 3], dtype='int64')

In [126]:
ind.set_names(["apple"], inplace=True)
ind.name = "bob"
ind

Int64Index([1, 2, 3], dtype='int64', name='bob')

In [127]:
ind

Int64Index([1, 2, 3], dtype='int64', name='bob')

### Set an Index

In [33]:
data = pd.DataFrame({'a': np.arange(6),
                   'b': np.random.randn(6),
                    'c': np.random.randn(6)})
indexed1 = data.set_index('c')
indexed1

a         b
c                     
-1.581814  0  0.882811
-0.361426  1 -0.179826
-0.146558  2  1.664804
 1.489749  3 -0.646629
-1.036543  4  0.243737
-0.439592  5 -0.308829

In [34]:
indexed2 = data.set_index(['a', 'b'])
indexed2

c
a b                  
0  0.882811 -1.581814
1 -0.179826 -0.361426
2  1.664804 -0.146558
3 -0.646629  1.489749
4  0.243737 -1.036543
5 -0.308829 -0.439592

In [35]:
data.set_index('c', drop = False)
data.set_index(['a', 'b'], inplace = True)
data

c
a b                  
0  0.882811 -1.581814
1 -0.179826 -0.361426
2  1.664804 -0.146558
3 -0.646629  1.489749
4  0.243737 -1.036543
5 -0.308829 -0.439592

### Dictionary Like GET() Method

In [134]:
s = pd.Series([1,2,3], index =['a', 'b', 'c'])
s.get('a')

1

In [135]:
s.get('x', default = -1)

-1

### Hierarchical Indexing(Multiindex)

In [141]:
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo","qux","qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two" ]
]
tuples = list(zip(*arrays))
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [146]:
index = pd.MultiIndex.from_tuples(tuples, name=["first", "second"])
index

s = pd.Series(np.random.randn(8), index=index)
s

first  second
bar    one      -0.242778
       two      -0.088573
baz    one      -0.433207
       two       0.500300
foo    one      -0.651285
       two       1.630053
qux    one      -1.474108
       two      -1.991748
dtype: float64

In [149]:
iterables = [["bar", "baz", "foo", "qux"], ["one", "two"]]
pd.MultiIndex.from_product(iterables, names=["first", "second"])

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

In [150]:
df = pd.DataFrame(
    [["bar", "one"], ["bar", "two"], ["foo", "one"], ["foo", "two"]],
    columns = ["first", "second"])
pd.MultiIndex.from_frame(df)

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('foo', 'one'),
            ('foo', 'two')],
           names=['first', 'second'])

In [151]:
arrays = [
    np.array(["bar", "bar", "baz", "baz", "foo", "foo","qux","qux"]),
    np.array(["one", "two", "one", "two", "one", "two", "one", "two"])
  ]
s = pd.Series(np.random.randn(8), index=arrays)
s

bar  one    0.019906
     two    0.645042
baz  one   -0.350459
     two   -0.655884
foo  one    0.176371
     two    0.839739
qux  one    0.077800
     two    0.146319
dtype: float64

In [152]:
df = pd.DataFrame(np.random.randn(8,4), index=arrays)
df

0         1         2         3
bar one  0.366434  1.507977  1.041192  0.116686
    two  1.489353 -1.859758  0.045559 -0.091599
baz one  1.128861  1.158570  0.893629 -0.654622
    two -2.147005 -0.639472 -2.536179 -1.222218
foo one  1.140749  0.501673  1.153832 -2.613389
    two  0.986360  0.125709  1.301576 -0.932825
qux one -0.418611  0.354751 -2.888549 -0.175847
    two  0.606538  1.588124  0.175829 -0.322498

In [154]:
df = pd.DataFrame(np.random.randn(3,8), index = ["A", "B", "C"], columns=index)
df

first        bar                 baz                 foo                 qux  \
second       one       two       one       two       one       two       one   
A      -1.874101 -0.671249  0.969537  1.182523 -1.553448  0.106184 -0.271381   
B      -0.979781 -0.524875 -1.402355  0.479224  0.150560  0.134859 -0.406927   
C      -2.348514 -0.239198 -0.685120 -0.539661 -1.695786 -0.087680 -0.721760   

first             
second       two  
A       0.526219  
B       1.440809  
C       1.194566

In [156]:
pd.DataFrame(np.random.randn(6,6), index=index[:6], columns = index[:6])

first              bar                 baz                 foo          
second             one       two       one       two       one       two
first second                                                            
bar   one    -0.497503 -1.375841  0.383706 -0.779071  0.772495 -0.482401
      two     1.214041 -0.090452 -0.747012 -0.609915  0.254563 -0.255851
baz   one    -0.007083 -0.045733 -0.850406 -0.592207 -1.677196 -0.638520
      two     0.710708 -1.594688 -0.849302  0.894318 -0.304187  0.357710
foo   one    -0.661149  0.344341  0.008627  0.073220  1.404544 -0.277354
      two     0.340586 -0.481577  0.493801  0.440860 -0.552510 -0.281742

In [157]:
pd.Series(np.random.randn(8), index=tuples)

(bar, one)    1.460907
(bar, two)   -1.857365
(baz, one)    0.139424
(baz, two)    0.161902
(foo, one)   -0.853702
(foo, two)   -0.342533
(qux, one)   -1.856701
(qux, two)    0.292093
dtype: float64

## Reconstructing the Level Labels

In [158]:
index.get_level_values(0)

Index(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'], dtype='object', name='first')

In [159]:
index.get_level_values("second")

Index(['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two'], dtype='object', name='second')

## Basic Indexing on axis with Multiindex

In [160]:
df["bar"]

second       one       two
A      -1.874101 -0.671249
B      -0.979781 -0.524875
C      -2.348514 -0.239198

In [161]:
df["bar", "one"]

A   -1.874101
B   -0.979781
C   -2.348514
Name: (bar, one), dtype: float64

In [162]:
df["bar"]["one"]

A   -1.874101
B   -0.979781
C   -2.348514
Name: one, dtype: float64

In [163]:
s["qux"]

one    0.077800
two    0.146319
dtype: float64

## Sorting a Multiindex

In [165]:
import random
random.shuffle(tuples)
s = pd.Series(np.random.randn(8), index = pd.MultiIndex.from_tuples(tuples))
s

baz  two    0.222552
bar  two    2.124190
qux  two    1.345402
baz  one    0.897418
foo  two   -0.135778
bar  one   -0.254744
foo  one   -0.514548
qux  one    0.029415
dtype: float64

In [166]:
s.sort_index()

bar  one   -0.254744
     two    2.124190
baz  one    0.897418
     two    0.222552
foo  one   -0.514548
     two   -0.135778
qux  one    0.029415
     two    1.345402
dtype: float64

In [167]:
s.sort_index(level=0)

bar  one   -0.254744
     two    2.124190
baz  one    0.897418
     two    0.222552
foo  one   -0.514548
     two   -0.135778
qux  one    0.029415
     two    1.345402
dtype: float64

In [168]:
s.sort_index(level=1)

bar  one   -0.254744
baz  one    0.897418
foo  one   -0.514548
qux  one    0.029415
bar  two    2.124190
baz  two    0.222552
foo  two   -0.135778
qux  two    1.345402
dtype: float64

In [170]:
s.index.set_names(["L1", "L2"], inplace = True)
s.sort_index(level = "L1")

L1   L2 
bar  one   -0.254744
     two    2.124190
baz  one    0.897418
     two    0.222552
foo  one   -0.514548
     two   -0.135778
qux  one    0.029415
     two    1.345402
dtype: float64

In [171]:
s.sort_index(level = "L2")

L1   L2 
bar  one   -0.254744
baz  one    0.897418
foo  one   -0.514548
qux  one    0.029415
bar  two    2.124190
baz  two    0.222552
foo  two   -0.135778
qux  two    1.345402
dtype: float64

In [172]:
df.T.sort_index(level=1, axis=1)

A         B         C
first second                              
bar   one    -1.874101 -0.979781 -2.348514
      two    -0.671249 -0.524875 -0.239198
baz   one     0.969537 -1.402355 -0.685120
      two     1.182523  0.479224 -0.539661
foo   one    -1.553448  0.150560 -1.695786
      two     0.106184  0.134859 -0.087680
qux   one    -0.271381 -0.406927 -0.721760
      two     0.526219  1.440809  1.194566

## Categorical Data

In [174]:
# specifying dtype="category" when constructing a series
s = pd.Series(["a", "b", "c", "a"], dtype = "category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): ['a', 'b', 'c']

In [175]:
# converting an existing Series or column to category type

df = pd.DataFrame({"A": ["a", "b", "c", "a"]})
df["B"] = df["A"].astype("category")
df

A  B
0  a  a
1  b  b
2  c  c
3  a  a

### pd.Categorical

In [177]:
import pandas as pd 
cat = pd.Categorical(['a', 'b', 'c', 'a', 'b', 'c'])
print(cat)

['a', 'b', 'c', 'a', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']


In [181]:
import pandas as pd 
cat = pd.Categorical(['a', 'b', 'c', 'a', 'b', 'c', 'd'], ['c', 'b', 'a'])
print(cat)

['a', 'b', 'c', 'a', 'b', 'c', NaN]
Categories (3, object): ['c', 'b', 'a']


In [182]:
import pandas as pd 
cat = pd.Categorical(['a', 'b', 'c', 'a', 'b', 'c', 'd'], ['c', 'b', 'a'], ordered = True)
print(cat)

['a', 'b', 'c', 'a', 'b', 'c', NaN]
Categories (3, object): ['c' < 'b' < 'a']


In [186]:
import pandas as pd 
import numpy as np 
cat = pd.Categorical(["a", "c", "c", np.nan], categories=["b", "a", "c"])
df = pd.DataFrame({"cat":cat, "s":["a", "c", "c", np.nan]})
print(df.describe)
print("\n")
print(df["cat"].describe())

<bound method NDFrame.describe of    cat    s
0    a    a
1    c    c
2    c    c
3  NaN  NaN>


count     3
unique    2
top       c
freq      2
Name: cat, dtype: object


In [188]:
# working with all categories

s = pd.Series(["a", "b", "c", "a"], dtype="category")
s.cat.categories

Index(['a', 'b', 'c'], dtype='object')

In [189]:
s.cat.ordered

False

In [190]:
s = pd.Series(pd.Categorical(["a", "b", "c", "a"], categories=["c", "b", "a"]))
s.cat.categories

Index(['c', 'b', 'a'], dtype='object')

In [191]:
s.cat.ordered

False

In [192]:
# unique()
import numpy as np
import pandas as pd
pd.Series([2,4,3,3], name='P').unique()

array([2, 4, 3], dtype=int64)

In [194]:
# renaming categories
s = pd.Series(["a", "b", "c", "a"], dtype ="category")
s
print("\n")
s.cat.categories = ["Group %s" %g for g in s.cat.categories]
s                  

0    Group a
1    Group b
2    Group c
3    Group a
dtype: category
Categories (3, object): ['Group a', 'Group b', 'Group c']

In [195]:
s = s.cat.rename_categories([1,2,3])
s

0    1
1    2
2    3
3    1
dtype: category
Categories (3, int64): [1, 2, 3]

In [197]:
s = s.cat.rename_categories({1:"x", 2:"y", 3:"z"})
s

0    x
1    y
2    z
3    x
dtype: category
Categories (3, object): ['x', 'y', 'z']

In [198]:
# appending new categories

s = s.cat.add_categories([4])
s.cat.categories

Index(['x', 'y', 'z', 4], dtype='object')

In [199]:
s

0    x
1    y
2    z
3    x
dtype: category
Categories (4, object): ['x', 'y', 'z', 4]

In [200]:
# removing categories
s = s.cat.remove_categories([4])
s

0    x
1    y
2    z
3    x
dtype: category
Categories (3, object): ['x', 'y', 'z']

In [201]:
# removing unused categories
s = pd.Series(pd.Categorical(["a", "b", "a"], categories=["a", "b", "c", "d"]))
s

0    a
1    b
2    a
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [203]:
s = s.cat.remove_unused_categories()
s

0    a
1    b
2    a
dtype: category
Categories (2, object): ['a', 'b']

In [208]:
# cut()
df = pd.DataFrame({"value":np.random.randint(0, 100, 20)})
labels = ["{0} - {1}".format(i, i+9) for i in range(0,100,10)]
df["group"] = pd.cut(df.value,range(0,105,10), right=False,labels=labels)
df

value    group
0      40  40 - 49
1      97  90 - 99
2      52  50 - 59
3      91  90 - 99
4      83  80 - 89
5      58  50 - 59
6      95  90 - 99
7      83  80 - 89
8      21  20 - 29
9      67  60 - 69
10     52  50 - 59
11     92  90 - 99
12     66  60 - 69
13     46  40 - 49
14     43  40 - 49
15     52  50 - 59
16     18  10 - 19
17     52  50 - 59
18     52  50 - 59
19     85  80 - 89

In [207]:
df = pd.DataFrame({"value": np.random.randint(0, 100, 20)})

labels = ["{0} - {1}".format(i, i + 9) for i in range(0, 100, 10)]

df["group"] = pd.cut(df.value, range(0, 105, 10), right=False, labels=labels)

df.head(10)

value    group
0     11  10 - 19
1     48  40 - 49
2     78  70 - 79
3     99  90 - 99
4     42  40 - 49
5     82  80 - 89
6      1    0 - 9
7      1    0 - 9
8     81  80 - 89
9     22  20 - 29

# Vectorization in Python

In [1]:
# Dot Product
import time
import numpy
import array
a = array.array('q')
for i in range(100000):
    a.append(i)
b = array.array('q')
for i in range(100000, 200000):
    b.append(i)
# classic dot product of vector implementation 
tic = time.process_time()
dot = 0.0;
for i in range(len(a)):
    dot += a[i] * b[i]
toc = time.process_time()
print("dot_product = " + str(dot));
print("Computation time = " + str(1000*(toc - tic)) + "ms")
n_tic = time.process_time()
n_dot_product = numpy.dot(a,b)
n_toc = time.process_time()
print("\nn_dot_product= "+ str(n_dot_product))
print("Computation time= "+ str(1000*(n_toc - n_tic)) + "ms")

dot_product = 833323333350000.0
Computation time = 78.125ms

n_dot_product= 833323333350000
Computation time= 0.0ms


In [5]:
# Inner Product
import time
import numpy
import array
a = array.array('i')
for i in range(200):
    a.append(i)
b = array.array('i')
for i in range(200, 400):
    b.append(i)
# classic outer product of vector implementation 
tic = time.process_time()
outer_product = numpy.zeros((200, 200))
for i in range(len(a)):
    for j in range(len(b)):
        outer_product[i][j] = a[i] * b[j]

toc = time.process_time()
print("outer_product = " + str(outer_product))
print("Computation time = " + str(1000*(toc - tic)) + "ms")
n_tic = time.process_time()
outer_product = numpy.outer(a,b)
n_toc = time.process_time()
print("\nouter_product= "+ str(outer_product))
print("Computation time= "+ str(1000*(n_toc - n_tic)) + "ms")

outer_product = [[    0.     0.     0. ...     0.     0.     0.]
 [  200.   201.   202. ...   397.   398.   399.]
 [  400.   402.   404. ...   794.   796.   798.]
 ...
 [39400. 39597. 39794. ... 78209. 78406. 78603.]
 [39600. 39798. 39996. ... 78606. 78804. 79002.]
 [39800. 39999. 40198. ... 79003. 79202. 79401.]]
Computation time = 46.875ms

outer_product= [[    0     0     0 ...     0     0     0]
 [  200   201   202 ...   397   398   399]
 [  400   402   404 ...   794   796   798]
 ...
 [39400 39597 39794 ... 78209 78406 78603]
 [39600 39798 39996 ... 78606 78804 79002]
 [39800 39999 40198 ... 79003 79202 79401]]
Computation time= 0.0ms


In [7]:
# Element wise Product
import time
import numpy
import array
a = array.array('i')
for i in range(50000):
    a.append(i)
b = array.array('i')
for i in range(50000, 100000):
    b.append(i)
# classic element wise product of vectors implementation 
vector = numpy.zeros((50000))
tic = time.process_time()
for i in range(len(a)):
    vector[i] = a[i] * b[j]
toc = time.process_time()
print("Element wise Product = " + str(vector))
print("\nComputation time = " + str(1000*(toc - tic)) + "ms")
n_tic = time.process_time()
vector = numpy.multiply(a,b)
n_toc = time.process_time()
print("\nElement wise Product= "+ str(vector))
print("Computation time= "+ str(1000*(n_toc - n_tic)) + "ms")

Element wise Product = [0.0000000e+00 5.0199000e+04 1.0039800e+05 ... 2.5097994e+09 2.5098496e+09
 2.5098998e+09]

Computation time = 46.875ms

Element wise Product= [        0     50001    100004 ... 704582713 704732708 704882705]
Computation time= 0.0ms


## Pandas Vectorized Methods

In [13]:
import pandas as pd
import numpy as np
columns = ['one', 'two']
index = ['a', 'b', 'c', 'd']
one = [1, 2, 3, 4]
two = [1, 2, 3, 4]
d = {
    'one':one,
    'two':two
}
df = pd.DataFrame(d,columns=columns,index=index)
df

one  two
a    1    1
b    2    2
c    3    3
d    4    4

In [12]:
df.apply(np.mean)

one    2.5
two    2.5
dtype: float64

In [14]:
df.mean()

one    2.5
two    2.5
dtype: float64

In [17]:
df['one'].map(lambda x : x>=1)

a    True
b    True
c    True
d    True
Name: one, dtype: bool

In [18]:
df.applymap(lambda x : x>=1 )

one   two
a  True  True
b  True  True
c  True  True
d  True  True