In [1]:
# List

import numpy as np
import time
import sys
s = range(1000)
print(sys.getsizeof(5)*len(s))

28000


In [6]:
# Numpy
D = np.arange(1000)
print(D.size*D.itemsize)

4000


In [7]:
import time
import numpy as np

SIZE = 1_000_000

L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x, y) for x, y in zip(L1, L2)]
print('Python list: ')
print((time.time() - start) * 1000)
print()

start = time.time()
result = A1 + A2
print('NumPy array: ')
print((time.time() - start) * 1000)

Python list: 
339.8253917694092

NumPy array: 
100.10743141174316


In [8]:
import numpy as np
arr = np.array([[1,2,3],
              [4,2,5]])
print("Array is of type: ", type(arr))
print("No of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [10]:
import numpy as np
a = np.array([[1,2,4], [5,8,7]], dtype = 'float')
print("Array created using passed list: \n", a)
b = np.array((1,3,2))
print("\nArray created using passed tuple: \n", b)
c = np.zeros((3,4))
print("\nAn array initialized with all zeros: \n", c)
d = np.full((3,3),6,dtype = 'complex')
print("\nAn array initialized with all 6s."
       "Array type is complex: \n", d)
e = np.random.random((2,2))
print("\nA random array: \n", e)
f = np.arange(0,30,5)
print("\n A sequential array with steps of 5:\n",f)


Array created using passed list: 
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple: 
 [1 3 2]

An array initialized with all zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex: 
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array: 
 [[0.7751991  0.98163014]
 [0.95512599 0.5520604 ]]

 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [11]:
import numpy as np
arr = np.array([[-1,2,0,4],
               [4,-0.5,6,0],
               [2.6,0,7,8],
               [3,-7,4,2.0]])
temp = arr[:2, ::2]
print("Array with first 2 rows and alternate"
           "columns(0 and 2):\n", temp)
temp = arr[[0,1,2,3],[3,2,1,0]]
print("\n Elements at indices (0,3), (1,2), (2,1),"
                       "(3,0):\n",temp)
cond= arr > 0
temp = arr[cond]
print("\n Elements greater than o:\n", temp)


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

 Elements at indices (0,3), (1,2), (2,1),(3,0):
 [4. 6. 0. 3.]

 Elements greater than o:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [12]:
import numpy as np
a = np.array([1,2,5,3])
print("Adding 1 to every element: ",a+1)
print("Substring 3 from each element: ",a-3)
print("Multiplying each element by 10: ",a*10)
print("Squaring each element: ",a**2)

a *= 2
print("Doubled each element of original array: ",a)
a = np.array([[1,2,3], [3,4,5], [9,6,0]])
print("\n Original array: \n",a)
print("Transpose of array:\n",a.T)

Adding 1 to every element:  [2 3 6 4]
Substring 3 from each element:  [-2 -1  2  0]
Multiplying each element by 10:  [10 20 50 30]
Squaring each element:  [ 1  4 25  9]
Doubled each element of original array:  [ 2  4 10  6]

 Original array: 
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [17]:
# Numpy sum with Axis 0

import numpy as np
np_array_2d = np.arange(0,6).reshape([2,3])
print(np_array_2d)
a = np.sum(np_array_2d,axis = 0)
print(a)

[[0 1 2]
 [3 4 5]]
[3 5 7]


In [18]:
# Numpy sum with Axis 1

import numpy as np
np_array_2d = np.arange(0,6).reshape([2,3])
print(np_array_2d)
a = np.sum(np_array_2d,axis = 1)
print(a)

[[0 1 2]
 [3 4 5]]
[ 3 12]


In [20]:
# # Concatenate Np arrays with axis 0
import numpy as np
np_array_1 = np.array([[1,1,1],[1,1,1]])
np_array_2 = np.array([[2,2,2],[2,2,2]])
print(np_array_1)
print(np_array_2)
a = np.concatenate([np_array_1, np_array_2], axis=0)
print(a)

[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


In [21]:
# Concatenate Np arrays with axis 1
import numpy as np
np_array_1 = np.array([[1,1,1],[1,1,1]])
np_array_2 = np.array([[2,2,2],[2,2,2]])
print(np_array_1)
print(np_array_2)
a = np.concatenate([np_array_1, np_array_2], axis=1)
print(a)

[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [22]:
# Concatenate Numpy arrays with axis 1
import numpy as np
np_array_1 = np.array([[1,1,1],[1,1,1]])
np_array_2 = np.array([[2,2,2],[2,2,2]])
print(np_array_1)
print(np_array_2)
a = np.concatenate([np_array_1, np_array_2], axis=0)
b = np.concatenate([np_array_1, np_array_2], axis=1)
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [23]:
# concatenate two 1D arrays with Np axis in python
import numpy as np
np_array_1 = np.array([1,1,1])
np_array_2 = np.array([2,2,2])
print(np_array_1)
print(np_array_2)
a = np.concatenate([np_array_1, np_array_2], axis=0)
b = np.concatenate([np_array_1, np_array_2], axis=1)
print(a)
print(b)

[1 1 1]
[2 2 2]


AxisError: axis 1 is out of bounds for array of dimension 1

In [24]:
# Unary Operator
import numpy as np
arr = np.array([[1,5,6],
               [4,7,2],
               [3,1,9]])
print("Largest element is: ", arr.max())
print("Row-wise maximum elements: ", arr.max(axis=1))
print("Column-wise minimum elements: ", arr.min(axis=0))
print("Sum of all array elements: ",arr.sum())
print("Cumulative sum along each row: \n", arr.cumsum(axis=1))


Largest element is:  9
Row-wise maximum elements:  [6 7 9]
Column-wise minimum elements:  [1 1 2]
Sum of all array elements:  38
Cumulative sum along each row: 
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [25]:
import numpy as np
a = np.array([[1,2],
             [3,4]])
b = np.array([[3,4],
             [2,1]])
print("Array sum:\n", a + b)
print("Array multiplication:\n", a * b)
print("Matrix multiplication:\n", a.dot(b))



Array sum:
 [[4 6]
 [5 5]]
Array multiplication:
 [[3 8]
 [6 4]]
Matrix multiplication:
 [[ 7  6]
 [17 16]]


In [26]:
# Universal Functions

import numpy as np
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements: ",np.sin(a))
a = np.array([0,1,2,3])
print("Exponent of array elements: ", np.exp(a))
print("Square root of array elements: ",np.sqrt(a))

Sine values of array elements:  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements:  [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements:  [0.         1.         1.41421356 1.73205081]


In [27]:
# Sorting Array
import numpy as np
a = np.array([[1,4,2],
             [3,4,6],
             [0,-1,5]])
print("Array elements in sorted order: \n", np.sort(a,axis = None))
print("Row wise sorted array:\n", np.sort(a,axis = 1))
print("Column wise sort by applying merge sort:\n", np.sort(a,axis=0, kind='mergesort'))
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa',float)]
values = [('Hritik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
arr = np.array(values, dtype = dtypes)
print("\n Array sorted by names: \n", np.sort(arr, order = 'name'))
print("Array sorted by graduation year and then cgpa: \n", np.sort(arr, order = ['grad_year', 'cgpa']))

Array elements in sorted order: 
 [-1  0  1  2  3  4  4  5  6]
Row wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

 Array sorted by names: 
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hritik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa: 
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hritik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [28]:
#  Advanced Indexing
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is: ')
print(x)
print('\n')
rows = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])
y = x[rows, cols]
print('The corner elements of this array are: ')
print(y)

Our array is: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are: 
[[ 0  2]
 [ 9 11]]


In [30]:
import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is: ')
print(x)
print('\n')
z = x[1:4, 1:3]
print('After slicing, our array becomes: ')
print(z)
print('\n')
y = x[1:4, [1,2]]
print('Slicing using advanced index for column: ')
print(x)

Our array is: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes: 
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
# Iteration Over Array

import numpy as np
a = np.arange(0, 60, 5)
a = a.reshape(3,4)
print('Original array is: ')
print(a)
print('\n')
print('Modified array is: ')
for x in np.nditer(a):
    print(x)

Original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is: 
0
5
10
15
20
25
30
35
40
45
50
55


In [33]:
import numpy as np
a = np.arange(0, 60, 5)
a = a.reshape(3,4)
print('Original array is: ')
print(a)
print('\n')
print('Transpose of the original array is: ')
b = a.T
print(b)
print('\n')
print('Modified array is: ')
for x in np.nditer(a):
    print(x,)

Original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is: 
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is: 
0
5
10
15
20
25
30
35
40
45
50
55


In [35]:
import numpy as np
a = np.arange(0, 60, 5)
a = a.reshape(3,4)
print('Original array is: ')
print(a)
print('\n')
print('Transpose of the original array is: ')
b = a.T
print(b)
print('\n')
print('Sorted in C-style order: ')
c = b.copy(order = 'C')
print(c)
for x in np.nditer(c):
    print(x,)
print('\n')
print('Sorted in F-style order: ')
c = b.copy(order = 'F')
print(c)
for x in np.nditer(c):
    print(x,)

Original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is: 
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order: 
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order: 
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [38]:
#  Modifying Array Values
import numpy as np
a = np.arange(0, 60, 5)
a = a.reshape(3,4)
print('Original array is: ')
print(a)
print('\n')
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 2 * x
print('Modified array is: ')
print(a)

Original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is: 
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [42]:
import numpy as np
a = np.arange(0, 60, 5)
a = a.reshape(3,4)
print('Original array is: ')
print(a)
print('\n')
print('Modified array is: ')
for x in np.nditer(a,flags = ['external_loop'],order = 'F'):
    print(x,)

Original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is: 
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [43]:
#  Broadcasting Iteration
import numpy as np
a = np.arange(0, 60, 5)
a = a.reshape(3,4)
print('Forst array is: ')
print(a)
print('\n')
print('Second array is: ')
b = np.array([1,2,3,4], dtype = int)
print(b)
print("\n")
print('Modified array is: ')
for x,y in np.nditer([a,b]):
    print("%d:%d" % (x,y),)

Forst array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is: 
[1 2 3 4]


Modified array is: 
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [44]:
#  Stacking

import numpy as np
a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
             [7,8]])
print("Vertical stacking: \n", np.vstack((a,b)))
print("Horizontal stacking: \n", np.hstack((a,b)))
c = [5,6]
print("\n Column Stacking: \n", np.column_stack((a,c)))
print("\n Concatenating to 2nd axis: \n", np.concatenate((a,b),1))

Vertical stacking: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stacking: 
 [[1 2 5 6]
 [3 4 7 8]]

 Column Stacking: 
 [[1 2 5]
 [3 4 6]]

 Concatenating to 2nd axis: 
 [[1 2 5 6]
 [3 4 7 8]]


In [45]:
# Splitting

import numpy as np
a = np.array([[1,3,5,7,9,11],
             [2,4,6,8,10,12]])
print("Splitting along horizontal axis into 2 parts: \n", np.hsplit(a,2))
print("Splitting along vertical axis into 2 parts: \n", np.vsplit(a,2))


Splitting along horizontal axis into 2 parts: 
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
Splitting along vertical axis into 2 parts: 
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [46]:
# Broadcasting Examples

import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)
c = [2.0, 2.0, 2.0]
print(a*c)

[2. 4. 6.]
[2. 4. 6.]


In [47]:
import numpy as np
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([0.0, 1.0, 2.0])
print(a[:, np.newaxis] + b)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [49]:
import numpy as np
today = np.datetime64('2017-02-12')
print("Date is: ", today)
print("Year is: ", np.datetime64(today, 'Y'))
dates = np.arange('2017-02', '2017-03', dtype = 'datetime64[D]')
print("\nDates of February, 2017:\n", dates)
print("Today is February:", today in dates)
dur = np.datetime64('2017-05-22') - np.datetime64('2016-05-22')
print("\n Np. of days: ", dur)
print("No. of weeks: ", np.timedelta64(dur, 'W'))
a = np.array(['2017-02-12', '2016-10-13', '2019-05-22'], dtype = 'datetime64')
print("\nDates in sorted order: ", np.sort(a))

Date is:  2017-02-12
Year is:  2017

Dates of February, 2017:
 ['2017-02-01' '2017-02-02' '2017-02-03' '2017-02-04' '2017-02-05'
 '2017-02-06' '2017-02-07' '2017-02-08' '2017-02-09' '2017-02-10'
 '2017-02-11' '2017-02-12' '2017-02-13' '2017-02-14' '2017-02-15'
 '2017-02-16' '2017-02-17' '2017-02-18' '2017-02-19' '2017-02-20'
 '2017-02-21' '2017-02-22' '2017-02-23' '2017-02-24' '2017-02-25'
 '2017-02-26' '2017-02-27' '2017-02-28']
Today is February: True

 Np. of days:  365 days
No. of weeks:  52 weeks

Dates in sorted order:  ['2016-10-13' '2017-02-12' '2019-05-22']


In [50]:
import numpy as np
a = np.arange(10,1,-2)
print("\n A sequential array with a negative step: \n",a)
newarr = a[np.array([3,1,2])]
print("\n Elements at these indices are: \n", newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are: 
 [4 8 6]


In [51]:
x = np.array([1,2,3,4,5,6,7,8,9])
arr = x[np.array([1,3,-3])]
print("\n Elements are: \n", arr)


 Elements are: 
 [2 4 7]


In [52]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
print(a[[0,1,2], [0,0,1]])

[1 3 6]
